name: flutter_grid_layout
description: Grid Layout (CSS) for Flutter as part of an adaptive design strategy.
version: 0.1.0
homepage: https://github.com/lyskouski/flutter_grid_layout
repository: https://github.com/lyskouski/flutter_grid_layout
issue_tracker: https://github.com/lyskouski/flutter_grid_layout/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
